import localFont from "next/font/local";
import {Outfit} from "next/font/google";

import "./globals.css";
//import { ClerkProvider } from "@clerk/nextjs/dist/types/components.server";
//import { ClerkProvider } from "@clerk/clerk-react";
 import { ClerkProvider } from "@clerk/nextjs";

const outfit = Outfit({subsets: ["latin"]});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Fetch the Clerk publishable key from the environment variables
  

  

  return (
        <html lang="en">
        <body
          className={outfit.className}
        >
          <ClerkProvider>
          {children}
          </ClerkProvider>
        </body>
      </html>
  );
}
